[env]
SHERPA_ONNX_LIB_DIR = { value = "../../game-video/engine/target/sherpa-onnx-prebuilt/sherpa-onnx-v1.13.2-osx-arm64-static-lib/lib", relative = true }
SHERPA_LIB_PATH = { value = "../../game-video/engine/target/debug/build/sherpa-rs-sys-97793a9c7ba5b002/out", relative = true }
